### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ivardensphere** [killjoy1221/Achievement-Get#2]
I am working on a customized private modpack and was curious if this supports things outside of vanilla.

I set up an test achievement:

{
        "id": "killWere",
        "name": "Hungry Like The Wolf",
        "desc": "Kill a Werewolf",
        "stat": "stat.killEntity.MoCreatures.Werewolf",
        "count": 1,
               "item": "MoCreatures:fur",
        "xPos": -2,
        "yPos": -1
}

The achievement shows on the tab as does the correct icon, but killing the creature itself does not fire off the completion of the achievement and completion is not obtained.

So does the "stat.killEntity" only support vanilla mobs?

Thanks.

**Comment by mattmess1221** [comment]
You'd have to ask the mocreatures dev. You can test if the stat exists by using the scoreboard or achievement command. 

There should also be a log if the stat doesn't exist.

**Comment by ivardensphere** [comment]
This can be closed. Forge does not auto track static fields for modded items automatically and it's up to the mod devs to put in statistics per entity/item.

https://github.com/MinecraftForge/MinecraftForge/issues/2454 as reference.
