### ISSUE TITLE
The Item field in the Json file

### ISSUE THREAD

**Issue by ivardensphere** [killjoy1221/Achievement-Get#3]
Hello,

get the following error:

https://gist.github.com/ivardensphere/273662c0fd80502af1a9

when using the item field with meta data per the example:

```
{
    "id": "pro",
    "name": "Pro",
    "desc": "Play for a month",
    "parent": "veteran",
    "color": "dark_red",
    "special": true,        
    "stat": "stat.playOneMinute",
    "count": 518400000,
    "item": 
    {
        "id": "minecraft:wool",
        "meta": "4"
    },      
    "xPos": 5,
    "yPos": 1
}   
```

Please let me know thanks.

**Comment by mattmess1221** [comment]
~~I have a big habit of making a change and never releasing it. I think it's been at least [4 months](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2394599-achievement-get-a-game-of-achievements?comment=18)~~

Edit: Are you using version 1.0.1?

**Comment by ivardensphere** [comment]
AchievementGet-1.7.10-1.0.1.rar

**Comment by mattmess1221** [comment]
I just published 1.0.2. The changes I thought were in 1.0.1 actually weren't. And this is 9 months after the fact. I had documented it and everything.

Downloads are both on curse and in releases here.

**Comment by ivardensphere** [comment]
Sorry for the late response. This works perfect now so thanks for the quick fix! Not sure why no one caught it prior but loving the mod. Thanks again!

**Comment by mattmess1221** [comment]
Someone actually did, but they posted about it on the forum and never
followed up.
